### ISSUE TITLE
Version number drift with PyPi

### ISSUE THREAD

**Issue by thisisparker** [alexdej/puzpy#27]
Hey there! Thank you thank you for this library, and I'm delighted to see some action in it lately. I wanted to flag that it looks like the release numbers here on Github have maybe drifted a bit from [the release history over on PyPI](https://pypi.org/project/puzpy/#history). For my purposes (I use `puzpy` as a library in a terminal-based solving interface) the PyPI release is pretty key, so if there's anything I can do to help get those in sync please let me know!

**Comment by micwoj92** [comment]
Ping @alexdej
