### ISSUE TITLE
UTF-8 characters in puzzles not readable

### ISSUE THREAD

**Issue by amclauth** [alexdej/puzpy#30]
FIrst off, good work! I found an "edge" case with the ISO-8859-1 encoding reads. Some puzzles have multi-byte characters in the clues. Probably even more true for other languages. https://ivan.mclauthlin.com/test/23-11-13-atl.puz is a small example. Clue 4 and 6 have emoji in them that look like they're UTF-8. I didn't debut into it to dig as I didn't see a super quick way to check. Thought I'd pass it along

**Comment by alexdej** [comment]
thank you for this. can you upload the original file? this looks edited. I am not seeing anything that looks like emoji in the binary file. 
![image](https://github.com/alexdej/puzpy/assets/34821/a0248741-cc42-4278-8f7c-327a66dcab94)

**Comment by amclauth** [comment]
Well shoot. Sorry to waste your time. You're right that it's not in the .puz file at all. I'm using xword-dl to get the .puz files and it must either not be in the source or if that does any encoding itself the problem is there, not with this project.  Thanks for checking. Wish I'd done some more digging first.

**Comment by alexdej** [comment]
xword-dl uses puz.py internally so it's possible there's an issue there. it would be helpful to get the raw bytes if possible.

**Comment by alexdej** [comment]
![Screenshot 2024-06-13 200529](https://github.com/alexdej/puzpy/assets/34821/d321ca44-3c1d-48b2-b178-f8e5b05d15be)

found the puzzle on atlantic
